Refatoração das camadas do script
tryber/nodejs-jwt-base-project pull request #13
Opened 2021-09-11 21:23 UTC by GabrielCoruja

2021-09-13 18:00 UTC, vinicius-vasconcelos requested changes

2021-09-13 18:00 UTC, vinicius-vasconcelos commented on models/user.js
> +  return userCreated.ops[0].username;
@GabrielCoruja fixa la em cima a versão do drive do MongoDB que queremos usar, nas versões mais novas esse **ops** não funciona mais.

2021-09-13 20:26 UTC, GabrielCoruja commented on models/connection.js
> +};
@vinicius-vasconcelos é a mesma connection, com diferença na exportação, uma coisa que eu vi é que o modo que é testado aqui não gerou bug

2021-09-15 20:19 UTC, vinicius-vasconcelos commented on models/connection.js
> +};
Boa boa, só perguntei por conta do nosso querido mongodb-memory-server :smile:

2021-09-15 20:19 UTC, vinicius-vasconcelos approved these changes

2021-09-15 20:20 UTC, italomourati approved these changes

2021-09-15 20:23 UTC, merged