[Melhoria Contínua] Trava versões de Bibliotecas
tryber/nodejs-jwt-base-project pull request #42
Opened 2022-11-10 12:42 UTC by apaulinhacarlos

## Qual é o objetivo dessa mudança?
Travar as versões das bibliotecas utilizadas no projeto para não haver futuros conflitos de versão.

## Existe alguma _issue_ relacionada?
[#1975](https://github.com/betrybe/conteudo-modular-desenvolvimento-web/issues/1975)

## Como essas mudanças resolvem a _issue_?
(resposta aqui)

2023-01-20 23:26 UTC, phtoselli approved these changes

2023-01-25 18:57 UTC, RafaelMedeirosGomes approved these changes

2023-01-26 12:08 UTC, Gammarkin approved these changes

2023-01-26 19:18 UTC, cleytonoliveira requested changes
Falta mapeamento na planilha

2023-02-17 17:17 UTC, cleytonoliveira approved these changes

2023-02-17 17:17 UTC, merged